### ISSUE TITLE
custom program error: 0xa7'

### ISSUE THREAD

**Issue by kiethuynh0904** [kiran-bhalerao/blog-dapp-solana#1]
I have cloned and run anchor test
but I have an error like below
![Screen Shot 2022-02-14 at 4 39 57 PM](https://user-images.githubusercontent.com/80958695/153838816-113cfeb3-9325-4d4a-99b1-3180640914e7.png)

Can you help me or explain what happen?

Thank You!

updated:
I have changed my wallet to my id.json directory (Anchor.toml)

CLOSED
I forgot to change the Program ID

**Comment by ashlinSajan** [comment]
Hi @kiran-bhalerao @kiethuynh0904 getting the following error when executing **anchor test**
![error](https://user-images.githubusercontent.com/34328137/160776160-c2df0c99-0093-45d9-b559-6542582c6a28.JPG
![error_1](https://user-images.githubusercontent.com/34328137/160776524-08477def-7d5c-41b4-8237-854d42d382db.JPG)
Could you please help me with this?I am totally new to solana
