### ISSUE TITLE
Issue while running anchor test

### ISSUE THREAD

**Issue by ashlinSajan** [kiran-bhalerao/blog-dapp-solana#2]
Hi @kiran-bhalerao @kiethuynh0904 getting the following error when executing **anchor test**
![error](https://user-images.githubusercontent.com/34328137/161034482-93c8353b-7ccb-41fb-bb95-9af2191060fd.JPG)
![error_1](https://user-images.githubusercontent.com/34328137/161034489-338555b9-6ccb-4553-9f46-f7f4cc933378.JPG)
Could you please help me with this

**Comment by rsa054** [comment]
Hey @ashlinSajan if you change your anchor-lang dependency version inside the program directory to  "0.16.1" then it will work fine, It seems the older version of anchor-lang was used for this project.

Hope to see the updated code real soon @kiran-bhalerao and thanks for the this one.

**Comment by kiran-bhalerao** [comment]
Hey @khatriamit, @ashlinSajan I have updated the program code to support the latest version of anchor-lang.

**Comment by ashlinSajan** [comment]
Thanks a lot @kiran-bhalerao I was able to deploy.
How can I view the UI for the same.
I read your article about the blog-dapp-solana.
But couldn't properly locate the UI files written in the article.
How can I run the UI?

**Comment by kiran-bhalerao** [comment]
> Thanks a lot @kiran-bhalerao I was able to deploy. How can I view the UI for the same. I read your article about the blog-dapp-solana. But couldn't properly locate the UI files written in the article. How can I run the UI?

[Here ](https://github.com/kiran-bhalerao/blog-dapp-solana#building-frontend)  you can find the frontend part of the tutorial.

If you have cloned the repo and you want to run Frontend UI then go to /app directory install dependencies with `npm i` or `yarn` and run the React app with` npm start` or `yarn start` script.
