### ISSUE TITLE
Test error!

### ISSUE THREAD

**Issue by nb312** [kiran-bhalerao/blog-dapp-solana#3]
When I run `anchor test`, it get this error
`thread 'main' panicked at 'Code not parseable: Error("the payer specified for an init constraint must be mutable.")', lang/syn/src/idl/file.rs:352:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
Message : 
- anchor-cli 0.23.0
- solana-cli 1.10.6 (src:8d5c7b7d; feat:3235626988)
- rustc 1.59.0 (9d1b2106e 2022-02-23)

**Comment by kiran-bhalerao** [comment]
Hey @nb312, it was the issue with an old version of anchor-lang dep.  I've updated the anchor-lang as well as the necessary code for it, please check the latest commit.

**Comment by nb312** [comment]
Thanks @kiran-bhalerao , but there also a error with 
`pub authority: Signer<'info>` should change to 
` #[account(mut)]
    pub authority: Signer<'info>,`

**Comment by kiran-bhalerao** [comment]
> Thanks @kiran-bhalerao , but there also a error with `pub authority: Signer<'info>` should change to ` #[account(mut)] pub authority: Signer<'info>,`

Hey, I've updated `pub authority: Signer<'info>`  to ` #[account(mut)] pub authority: Signer<'info>` where it is necessary. 
Could you provide the line number where you get that error?
