### ISSUE TITLE
unable to run the UI for blog-dapp

### ISSUE THREAD

**Issue by ashlinSajan** [kiran-bhalerao/blog-dapp-solana#5]
@kiran-bhalerao Getting the following error while running npm start at the app directory
![error_ui](https://user-images.githubusercontent.com/34328137/163798691-790fbb86-9b23-4660-aafc-2e2bf09c56fa.JPG)

**Comment by kiran-bhalerao** [comment]
@ashlinSajan try updating your nodejs version to v12 or above.

**Comment by ashlinSajan** [comment]
> @ashlinSajan try updating your nodejs version to v12 or above.

Updated.But got a new error
![error_2](https://user-images.githubusercontent.com/34328137/163975483-0fb1308e-e56e-404d-acae-01920fcd1282.JPG)

**Comment by kiran-bhalerao** [comment]
> > @ashlinSajan try updating your nodejs version to v12 or above.
> 
> Updated.But got a new error ![error_2](https://user-images.githubusercontent.com/34328137/163975483-0fb1308e-e56e-404d-acae-01920fcd1282.JPG)

This error is same as previous one.
Which nodejs version you have installed on your machine?

**Comment by ashlinSajan** [comment]
Hi @kiran-bhalerao the version of node is 12.22.12
Inspite of this I am getting the below issue
![UI_Error](https://user-images.githubusercontent.com/34328137/165042099-69a1057f-e9a4-420c-99b8-fd95f50fdc75.JPG)

**Comment by ashlinSajan** [comment]
@kiran-bhalerao Hi Kiran
I used node version 12.22.12.
But getting this error

https://user-images.githubusercontent.com/34328137/165042099-69a1057f-e9a4-420c-99b8-fd95f50fdc75.JPG
